version: "3.8"

services:
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_PORT:$MYSQL_PORT
    volumes:
      - school-register-db:/var/lib/mysql
    networks:
      - school-register-backend
  app:
    depends_on:
      - mysqldb
    build: ./app
    restart: on-failure
    env_file: ./.env
    ports:
      - $HTTP_PORT:$HTTP_PORT
    stdin_open: true
    tty: true
    volumes:
      - .m2:/root/.m2
    networks:
      - school-register-backend

volumes:
  school-register-db: 

networks:
  school-register-backend:
